# Generated by Django 4.2.9 on 2026-05-20 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('result', models.CharField(blank=True, choices=[('Benign', 'Benign'), ('Malignant', 'Malignant')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_score', models.FloatField(default=0.0)),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, verbose_name='Notes du médecin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(default=0.0, help_text='Temps de traitement en secondes')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
